version: '3.5'
services: 
    sqlserver: 
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        ports: 
            - "1433:1433"
        volumes: 
            - sqlserver
        environment: 
            SA_PASSWORD: Ab123456!
            ACCEPT_EULA: "Y"
volumes: 
    sqlserver:
